# Configuración de la Base de Datos
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=app_user
quarkus.datasource.password=app123
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/citas_medicas

# Hibernate ORM
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# MapStruct
quarkus.mapstruct.indexing.auto=true